### ISSUE TITLE
Failure due to partially removed --utf8 argument

### ISSUE THREAD

**Issue by martonmiklos** [pnlng/pdfoutliner#4]
Hello,

The recent master failing at me with the following error:

```
mm@lapos:~/Projektek/standards$ pdfoutliner "Part 3-01 Dispenser Application v2.33.txt" --inpdf "Part 3-01 Dispenser Application v2.33.pdf" 
Traceback (most recent call last):
  File "/home/mm/.local/bin/pdfoutliner", line 8, in <module>
    sys.exit(main())
  File "/home/mm/.local/lib/python3.8/site-packages/pdfoutliner/__main__.py", line 152, in main
    if args.utf8:
AttributeError: 'Namespace' object has no attribute 'utf8'

```

For me it looks like that half of the #3  PR have been removed from the master in cfd2d918f0cb85787c6164625d6a6f294feb294c

**Comment by alexispurslane** [comment]
Also having this issue.

**Comment by dangbert** [comment]
Also an issue with the latest version I just installed with pip (pdfoutliner==0.0.4)

**Comment by hychn** [comment]
same.

**Comment by ntevenhere** [comment]
The last working revision is 09e19d9d.
I built upon that version to fix another issue that I found against certain filenames.

For anyone that just wants to get pdfoutliner to work, you can install it with this command: 
```sh
git clone -b shell-injection-fix https://github.com/notevenaperson/pdfoutliner.git
```
